export const iranProvincesAndCapitals = [
  { province: "آذربایجان شرقی", capital: "تبریز" },
  { province: "آذربایجان غربی", capital: "ارومیه" },
  { province: "اردبیل", capital: "اردبیل" },
  { province: "اصفهان", capital: "اصفهان" },
  { province: "البرز", capital: "کرج" },
  { province: "ایلام", capital: "ایلام" },
  { province: "بوشهر", capital: "بوشهر" },
  { province: "تهران", capital: "تهران" },
  { province: "چهارمحال و بختیاری", capital: "شهرکرد" },
  { province: "خراسان جنوبی", capital: "بیرجند" },
  { province: "خراسان رضوی", capital: "مشهد" },
  { province: "خراسان شمالی", capital: "بجنورد" },
  { province: "خوزستان", capital: "اهواز" },
  { province: "زنجان", capital: "زنجان" },
  { province: "سمنان", capital: "سمنان" },
  { province: "سیستان و بلوچستان", capital: "زاهدان" },
  { province: "فارس", capital: "شیراز" },
  { province: "قزوین", capital: "قزوین" },
  { province: "قم", capital: "قم" },
  { province: "کردستان", capital: "سنندج" },
  { province: "کرمان", capital: "کرمان" },
  { province: "کرمانشاه", capital: "کرمانشاه" },
  { province: "کهگیلویه و بویراحمد", capital: "یاسوج" },
  { province: "گلستان", capital: "گرگان" },
  { province: "گیلان", capital: "رشت" },
  { province: "لرستان", capital: "خرم‌آباد" },
  { province: "مازندران", capital: "ساری" },
  { province: "مرکزی", capital: "اراک" },
  { province: "هرمزگان", capital: "بندرعباس" },
  { province: "همدان", capital: "همدان" },
  { province: "یزد", capital: "یزد" },
];
